spring:
  cloud:
    config:
      server:
        git:
          # GIT用户名
          username: # your_username
          # GIT密码
          password: # your_password
          # GIT仓库地址
          uri: https://github.com/fanlychie/mdfile.git
          # GIT仓库检索目录
          search-paths: config-center

server:
  port: 8888
  servlet:
    context-path: /