server:
  port: 9903

spring:
  application:
    name: PROVIDER-SERVICE

eureka:
  instance:
    # 服务名
    appname: ${spring.application.name}
  client:
    # 是否向Eureka Server获取所有的注册信息表
    fetch-registry: true
    # 与Eureka Server通讯的URL地址列
    service-url:
      defaultZone: http://my-eureka-server.com:9001/eureka/,http://my-eureka-server.com:9002/eureka/,http://my-eureka-server.com:9003/eureka/