server:
  port: 9900

spring:
  application:
    name: CLIENT-CONSUMER-STANDALONE

eureka:
  client:
    # 是否向Eureka Server获取所有的注册信息表
    fetch-registry: false
    # 与Eureka Server通讯的URL地址列
    service-url:
      defaultZone: http://my-eureka-server.gz.com:9001/eureka/,http://my-eureka-server.sz.com:9002/eureka/,http://my-eureka-server.zh.com:9003/eureka/

# 服务提供者配置
client:
  provider:
    # 服务提供者在Eureka Server中注册的服务ID
    service-id: CLIENT-PROVIDER-CLUSTER
    # 在Eureka Client中, 通过服务ID访问服务提供者
    service-url: http://${client.provider.service-id}/