server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  cloud:
    # 网关配置
    gateway:
      # 路由配置
      routes:
        # 路由ID(唯一)
        - id: CLIENT-PROVIDER-CLUSTER
          # 路由的转发地址, lb://注册到Eureka中的服务ID
          uri: lb://CLIENT-PROVIDER-CLUSTER
          # 断言, 匹配的才会路由到服务
          predicates:
            - Path=/provider/**
          filters:
            # /provider/* 的请求重写成 /*
            # (yml文档中`$`要写成`$\`)
            - RewritePath=/provider/(?<segment>.*), /$\{segment}
            # 重试机制
            - name: Retry
              args:
                # 重试3次
                retries: 3
                # 哪些状态需要重试
                # statuses 和 series 至少选其一
                # org.springframework.http.HttpStatus
                statuses:
                  - BAD_GATEWAY
                # 哪些状态需要重试
                # statuses 和 series 至少选其一
                # org.springframework.http.HttpStatus.Series
                series:
                  - SERVER_ERROR
                # 不支持POST, PUT
                methods:
                  - GET
                # 哪些异常需要重试
                exceptions:
                  - java.io.IOException
            # 自定义过滤器
            - MyPre=a, b
            - MyPost=c, d

# 服务发现与注册中心配置
eureka:
  instance:
    # 服务名
    appname: ${spring.application.name}
  client:
    # 是否把自己(当前服务)注册到服务注册和发现中心(以供其它服务发现)
    register-with-eureka: false
    # 是否从服务注册和发现中心检索同步注册的服务列表信息
    fetch-registry: true
    # 服务注册中心列表
    service-url:
      defaultZone: http://my-eureka-server.gz.com:9001/eureka/,http://my-eureka-server.sz.com:9002/eureka/,http://my-eureka-server.zh.com:9003/eureka/
