server:
  port: 9002

# Eureka客户端向Eureka Server注册的服务ID
# Eureka Server会将服务ID相同的服务集群在一起
spring:
  application:
    name: EUREKA-SERVER-CLUSTER

eureka:
  instance:
    # 实例的主机名
    # Eureka Server会自动过滤同一主机下相同的hostname, 因此如果是同一主机做集群必须定义不同的主机名
    hostname: my-eureka-server.sz.com
  client:
    # 是否把自己(当前服务)注册到服务注册和发现中心(以供其它服务发现)
    register-with-eureka: true
    # 是否从服务注册和发现中心检索同步注册的服务列表信息
    fetch-registry: true
    # 服务注册中心列表
    service-url:
      defaultZone: http://my-eureka-server.gz.com:9001/eureka/,http://my-eureka-server.zh.com:9003/eureka/