server:
  port: 9003

# Eureka客户端向Eureka Server注册的服务ID
# Eureka Server会将服务ID相同的服务集群在一起
spring:
  application:
    name: EUREKA-SERVER-CLUSTER

eureka:
  instance:
    # 实例的主机名
    # Eureka Server会自动过滤相同的主机名, 因此集群时必须定义不同的主机名
    hostname: my-eureka-server.zh.com
  client:
    # 是否向Eureka Server注册自己，以供外部应用发现自己(集群开启)
    register-with-eureka: true
    # 是否向Eureka Server获取所有的注册信息表(集群开启)
    fetch-registry: true
    # 与Eureka Server通讯的URL地址列
    service-url:
      defaultZone: http://my-eureka-server.gz.com:9001/eureka/,http://my-eureka-server.sz.com:9002/eureka/