server:
  port: 9000

eureka:
  instance:
    # 实例的主机名
    hostname: EUREKA-SERVER-SINGLE
  client:
    # 是否向Eureka Server注册自己，以供外部应用发现自己(单实例不需要开启)
    register-with-eureka: false
    # 是否向Eureka Server获取所有的注册信息表(单实例不需要开启)
    fetch-registry: false
    # 与Eureka Server通讯的URL地址列
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
