server:
  port: 9901

# Eureka客户端向Eureka Server注册的服务ID
# Eureka Server会将服务ID相同的服务集群在一起
spring:
  application:
    name: CLIENT-PROVIDER-CLUSTER

eureka:
  instance:
    # 服务名
    appname: ${spring.application.name}
  client:
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: true
    # 是否从其他的服务中心同步服务列表
    fetch-registry: true
    # 服务注册中心列表
    service-url:
      defaultZone: http://my-eureka-server.gz.com:9001/eureka/,http://my-eureka-server.sz.com:9002/eureka/,http://my-eureka-server.zh.com:9003/eureka/